# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: https://registry.npmjs.org/
      - name: Setup Git Author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Change version
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
      - run: npm install
      - run: npm run init:baileys
      - run: mv ./Baileys/lib ./baileys-lib
      - run: mv ./Baileys/WAProto ./WAProto
      - run: mv ./Baileys/WABinary ./WABinary
      - run: cp ./WABinary/Constants.js ./baileys-lib/Constants.js
      - run: mv ./Baileys/WASignalGroup ./WASignalGroup
      - name: Publish rc
        if: ${{ contains(github.event.release.tag_name, 'rc') }}
        run: |
          npm publish --tag rc
          git commit -a -m "bump: version bumped to ${{ github.event.release.tag_name }}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish beta
        if: ${{ contains(github.event.release.tag_name, 'beta') }}
        run: |
          npm publish --tag beta
          git commit -a -m "bump: version bumped to ${{ github.event.release.tag_name }}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish nightly
        if: ${{ contains(github.event.release.tag_name, 'nightly') }}
        run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish stable
        if: ${{ !contains(github.event.release.tag_name, 'rc') && !contains(github.event.release.tag_name, 'beta') && !contains(github.event.release.tag_name, 'nightly') }}
        run: |
          npm publish
          git commit -a -m "bump: version bumped to ${{ github.event.release.tag_name }}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          tags: false
